[package]
name = "bulls-den"
version = "0.1.0"
description = "Bull's Den - $ANSEM-only moderated prediction market"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "bulls_den"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = "0.30.1"
anchor-spl = "0.30.1"
